- name: copy cassandra template configuration to host
  template:
    src: files/cassandra.yml.j2
    dest: /etc/cassandra/default.conf/cassandra.yaml
    mode: '0644'
- name: update jmx_port
  lineinfile:
    path: /etc/cassandra/default.conf/cassandra-env.sh
    regexp: '^JMX_PORT='
    line: JMX_PORT="{{ _JMX_PORT }}"
- name: update mx4j_address
  lineinfile:
    path: /etc/cassandra/default.conf/cassandra-env.sh
    regexp: '^#MX4J_ADDRESS='
    line: MX4J_ADDRESS="-Dmx4jaddress={{ _DMX_ADDRESS }}"
- name: update mx4j_port
  lineinfile:
    path: /etc/cassandra/default.conf/cassandra-env.sh
    regexp: '^#MX4J_PORT='
    line: MX4J_PORT="-Dmx4jport={{ _DMX_PORT }}"
- name: copy mx4j-tools to cassandra
  copy:
    src: files/mx4j-tools.jar
    dest: /usr/share/cassandra/lib/
    force: yes