- name: add cassandra ports to firewall rule
  firewalld:
    zone: public
    port: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - 22/tcp
    - 7000/tcp
    - 7001/tcp
    - 7199/tcp
    - 9042/tcp
    - 9160/tcp
    - 9142/tcp
- name: restart firewall
  service:
    name: firewalld
    state: reloaded