- name: install required packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - ca-certificates
    - dirmngr
    - gnupg
    - software-properties-common
- name: add java 8 GPG key
  apt_key:
    url: https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public
    state: present
- name: add java 8 GPG repository
  apt_repository:
    repo: deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ buster main
    state: present
    filename: cassandra.sources.list
    update_cache: yes
- name: install java 8
  apt:
    name: adoptopenjdk-8-hotspot
    state: present
- name: update java_home and path
  shell: |
    export JAVA_HOME=$(dirname $(dirname $(readlink $(readlink $(which javac)))))
    export PATH=$PATH:$JAVA_HOME/bin
    export CLASSPATH=.:$JAVA_HOME/jre/lib:$JAVA_HOME/lib:$JAVA_HOME/lib/tools.jar