---
- hosts: cassandra
  become: yes
  vars_files:
    - ../config.vars
  tasks:
    - name: copy cassandra template configuration to host
      include: ../roles/configuration/configure_centos.yml
      when: ansible_distribution == 'CentOS'
    - name: copy cassandra template configuration to host
      include: ../roles/configuration/configure_debian_ubuntu.yml
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'