---
- hosts: cassandra
  become: yes
  tasks:
    - name: add Cassandra repo on CentOS
      shell: |
        echo "[cassandra]
        name=Apache Cassandra
        baseurl=https://www.apache.org/dist/cassandra/redhat/311x/
        gpgcheck=1
        repo_gpgcheck=1
        gpgkey=https://www.apache.org/dist/cassandra/KEYS" > /etc/yum.repos.d/cassandra.repo
    - name: install Cassandra on CentOS
      yum:
        name: cassandra
        state: latest