---
- hosts: cassandra
  become: yes
  tasks:
    - name: install Java JDK on CentOS
      yum:
        name: java-1.8.0-openjdk
        state: latest
      when: ansible_distribution == 'CentOS'
    - name: install Java JDK on Debian 9 or Ubuntu
      apt:
        name: openjdk-8-jre
        state: latest
        update_cache: yes
      when: ansible_distribution == 'Debian' and ansible_distribution_version >= "9" and ansible_distribution_version < 10 or ansible_distribution == 'Ubuntu' # <= sprawdzić wersję Debiana 9
    - name: install Java JDK 11 on Debian 10 # <= sprawdzić czy działa
      apt:
        name: default-jdk
        state: latest
        update_cache: yes
      when: ansible_distribution == 'Debian' and ansible_distribution_version >= "10" # <= sprawdzić wersję Debiana 10
    - name: Update JAVA_HOME and PATH
      shell: |
        export JAVA_HOME=$(dirname $(dirname $(readlink $(readlink $(which javac)))))
        export PATH=$PATH:$JAVA_HOME/bin
        export CLASSPATH=.:$JAVA_HOME/jre/lib:$JAVA_HOME/lib:$JAVA_HOME/lib/tools.jar