---
- hosts: cassandra
  become: yes
  vars_files:
    - ../config.vars
  tasks:
    - name: copy Cassandra template configuration to host
      template:
        src: ../utils/cassandra.yml.j2
        dest: /etc/cassandra/default.conf/cassandra.yaml
        mode: '0644'
    - name: udpate cassandra-env
      shell: |
        sed -i -r 's/JMX_PORT="7199"/JMX_PORT="{{ _JMX_PORT }}"/' /etc/cassandra/default.conf/cassandra-env.sh
        sed -i -r 's/#MX4J_ADDRESS="-Dmx4jaddress=127.0.0.1"/MX4J_ADDRESS="-Dmx4jaddress={{ _DMX_ADDRESS }}"/' /etc/cassandra/default.conf/cassandra-env.sh
        sed -i -r 's/#MX4J_PORT="-Dmx4jport=8081"/MX4J_PORT="-Dmx4jport={{ _DMX_PORT }}"/' /etc/cassandra/default.conf/cassandra-env.sh
    - name: update cassandra
      shell: |
        sed -i '72i s/^/#/' /etc/rc.d/init.d/cassandra
        sed -i '73i   runuser -u $CASSANDRA_OWNR -- $CASSANDRA_PROG -p $pid_file > $log_file 2>&1' /etc/rc.d/init.d/cassandra
        sed -i '74i   chown root.root $pid_file' /etc/rc.d/init.d/cassandra
    - name: copy MX4J to Cassandra
      copy:
        src: ../utils/mx4j-tools.jar
        dest: /usr/share/cassandra/lib/
        force: yes